spring:
  datasource:
    url: jdbc:h2:mem:moneytransferdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: h2
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
        engine:
          jdbc:
            spi:
              SqlExceptionHelper: DEBUG
server:
  port: 8080
